DATA:
  data_root: ./data/SBD/
  art_data_root: /cache/data
  train_list: ./data/SBD/train_list.txt
  art_train_list: /cache/data/train_list.txt
  val_list: ./data/SBD/val_list.txt
  art_val_list: /cache/data/val_list.txt
  classes: 21
  prefix: voc
  save_dir: ./checkpoints/
  backbone: resnet50
  pretrain_path: ./data/resnet_deepbase.ckpt
  art_pretrain_path: /cache/data/resnet_deepbase.ckpt
  ckpt: ./checkpoints/8P/voc-50_133.ckpt
  obs_save: obs://PSPnet/save_checkpoint/voc/

TRAIN:
  arch: psp
  feature_size: 60
  train_h: 473
  train_w: 473
  scale_min: 0.5  # minimum random scale
  scale_max: 2.0  # maximum random scale
  rotate_min: -10  # minimum random rotate
  rotate_max: 10  # maximum random rotate
  zoom_factor: 8  # zoom factor for final prediction during training, be in [1, 2, 4, 8]
  ignore_label: 255
  aux_weight: 0.4
  data_name:
  batch_size: 8  # batch size for training
  art_batch_size: 4
  batch_size_val: 8  # batch size for validation during training, memory and speed tradeoff
  base_lr: 0.005
  art_base_lr: 0.02
  epochs: 50
  start_epoch: 0
  power: 0.9
  momentum: 0.9
  weight_decay: 0.0001


TEST:
  test_list: ./dataset/voc2012/list/val.txt
  split: val  # split in [train, val and test]
  base_size: 512  # based size for scaling
  test_h: 473
  test_w: 473
  scales: [1.0]  # evaluation scales, ms as [0.5, 0.75, 1.0, 1.25, 1.5, 1.75]
  index_start: 0  # evaluation start index in list
  index_step: 0  # evaluation step index in list, 0 means to end
  result_path: ./result/voc/
  color_txt: ./voc2012/voc2012_colors.txt
  name_txt: ./voc2012/voc2012_names.txt
  device_target: Ascend


ONNX_INFER:
  onnx_path: /home/mindspore/pspnet/PSPNet/PSPNet.onnx
